Jarlin
JohnnyQuintero16/aplicativoWebLubrillantasJezreelAg pull request #18
Opened 2021-11-01 20:01 UTC by JarlinFonseca

Creando archivo servicios

2021-11-02 01:49 UTC, JohnnyQuintero16 requested changes
### Eso no me gusta, el archivo esta vacio apa

2021-11-05 16:18 UTC, JarlinFonseca commented
Ya agregue el slider en el html de servicios

2021-11-05 16:19 UTC, JarlinFonseca reviewed
Se agrego el slider en el html de Servicios

2021-11-05 20:08 UTC, JohnnyQuintero16 commented
ora si

2021-11-05 20:08 UTC, merged